language: python
python:
  - "2.7"
  - "3.5"
env:
  matrix:
   - DJANGO="Django>=1.9,<1.10"
   - DJANGO="Django>=1.10,<1.11"
   - DJANGO="Django>=1.11,<1.12"
branches:
    only:
        - master
# command to install dependencies
install:
  - pip install "$DJANGO"
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
before_script:
  - cp .env.example .env
  - python manage.py migrate
  - python manage.py collectstatic --noinput
# command to run tests
script:
    - coverage run manage.py test
after_success:
    - coveralls
