# Generated by Django 3.2.6 on 2023-08-07 17:09
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from django.contrib.auth import get_user_model

User = get_user_model()


def add_category_to_existing_data(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Category = apps.get_model('blog', 'Category')

    for article in Article.objects.all():
        category, is_created = Category.objects.get_or_create(title=article.category)
        Article.objects.filter(id=article.id).update(category=category.id)


def add_updated_to_existing_data(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Article.objects.all().update(updated=models.F('created'))


def add_published_to_existing_data(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Article.objects.all().update(published=models.F('created'))


def add_status_to_existing_data(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Article.objects.all().update(status='p')


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(add_category_to_existing_data),

        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(add_published_to_existing_data),

        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'publish')], default='d', max_length=1),
        ),
        migrations.RunPython(add_status_to_existing_data),

        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(null=True, auto_now=True,),
        ),
        migrations.RunPython(add_updated_to_existing_data),

        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='articles', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),

        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='articles', to='blog.category'),
        ),

    ]
