version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 800:800
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "codecup.settings.production"
    command: >
      sh -c "
        ./manage.py migrate;
        ./manage.py compilemessages;
        ./manage.py collectstatic --noinput;
        ./manage.py init_guard;
        gunicorn --bind=0.0.0.0:8000 --timeout=90 --workers=10 --preload codecup.wsgi:application;
      "
    volumes:
      - .:/code
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/codecup:/var/log/codecup
      - cachedata:/cache
    ports:
      - 8000:8000
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./media/:/media/
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  cachedata: