version: '2'

volumes:
  postgres_data: {}

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'

  redis:
    image: redis:3.0
    ports:
      - '6379:6379'
