# Generated by Django 3.1.3 on 2020-11-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_auto_20201119_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to='guard.viewdetail'),
        ),
    ]
