# Generated by Django 3.1.3 on 2020-11-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0003_blockedip_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedip',
            name='url_path',
        ),
    ]
