# Generated by Django 3.2.20 on 2023-07-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(default='main', max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
